# Generated by Django 3.0.7 on 2020-06-07 10:46

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200607_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectioncase',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.DetectionCase._get_upload_to),
        ),
    ]
